const ShipActionDifficulties = {
  "Encourage":                     "<span style='color:#222222;font-weight:bold;'>10 target skill or 15 Diplomacy</span>",
  "Taunt":                         "<span style='color:#a96d0f;font-weight:bold;'>Enemy Average</span>",
  "Demand":                        "<span style='color:#a96d0f;font-weight:bold;'>Average</span>",
  "Hold It Together":              "<span style='color:#a96d0f;font-weight:bold;'>Average</span>",
  "Divert":                        "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Patch":                         "<span style='color:#222222;font-weight:bold;'>Variable</span>",
  "Maintenance Panel Access":      "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Scrying":                       "<span style='color:#188fbd;font-weight:bold;'>Enemy Scan</span>",
  "Eldritch Shot":                 "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Precognition":                  "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Swift Kick":                    "<span style='color:#a96d0f;font-weight:bold;'>Average</span>",
  "Stunt":                         "<span style='color:#222222;font-weight:bold;'>Variable</span>",
  "Fly":                           "",
  "Maneuver":                      "<span style='color:#a96d0f;font-weight:bold;'>Average</span>",
  "Target System":                 "<span style='color:#188fbd;font-weight:bold;'>Enemy Scan</span>",
  "Balance":                       "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Scan":                          "<span style='color:#188fbd;font-weight:bold;'>Enemy Scan</span>",
  "Hard Turn":                     "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Manual Realignment":            "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Visual Identification":         "<span style='color:#349f4a;font-weight:bold;'>Easy</span>",
  "Glide":                         "",
  "Quick Rescan":                  "<span style='color:#188fbd;font-weight:bold;'>Enemy Scan</span>",
  "Fire At Will":                  "",
  "Shoot":                         "",
  "Harrying Shot":                 "<span style='color:#222222;font-weight:bold;'>10 + enemy pilot rank</span>",
  "Snap Shot":                     "",
};
export default ShipActionDifficulties;