const ShipActionDescriptions = {
  "Encourage":                     "Boost another crew member's action by +2 (+4 on crit), DC 10 target skill or DC 15 Diplomacy",
  "Taunt":                         "Select a phase, Bluff or Intimidate check vs an enemy (DC = enemy DDC), selected phase -2 penalty all checks for 1d4 rounds, once per ship per combat",
  "Demand":                        "Intimidate another crew member before they do an action for +4 bonus (DC = DDC), once per target crew member per combat",
  "Hold It Together":              "Treat system as though it's critically damaged by 2 less phases for the rest of the round (DC = DDC)",
  "Divert":                        "Boost speed by 2, all science officer rolls by 2, make weapon dice rolls 1 into 2, or restore 5% shields (DC = ADC)",
  "Patch":                         "Patch a system to reduce the effects of critical damage",
  "Maintenance Panel Access":      "Done before a Divert, Acrobatics or Athletics check (DC = ADC), if successful the engineer can divert 2 systems instead of 1",
  "Scrying":                       "Scan an enemy ship using Mysticism to learn one level of things about it (DC = enemy SDC)",
  "Eldritch Shot":                 "Augment a weapon with Mysticism (DC = ADC). If successful, that weapon gets +5 range for its next attack",
  "Precognition":                  "Give the pilot a +2 circumstance bonus to Piloting at the beginning of the Helm phase (DC = ADC)",
  "Swift Kick":                    "Engineering check (DC = DDC), select 1 system, treat it as though it were 1 step less damaged for the rest of round, once per system per combat",
  "Stunt":                         "Perform a stunt",
  "Fly":                           "Normal movement",
  "Maneuver":                      "Normal movement, but you can also attempt Piloting check (DC = DDC) to reduce turn limit by 1 for this movement",
  "Target System":                 "Make attacks against a target system crit on a 19 as well as a 20 (DC = enemy SDC)",
  "Balance":                       "Rebalance the shields using Computers check (DC = ADC)",
  "Scan":                          "Scan an enemy ship using Computers to learn one level of things about it (DC = enemy SDC)",
  "Hard Turn":                     "Acrobatics or Athletics check (DC = ADC), pilot gets to make a single turn with a +1 turn range",
  "Manual Realignment":            "Acrobatics or Athletics check (DC = ADC), science officer gets 2 levels of information from a scan instead of 1",
  "Visual Identification":         "Computers/Engineering/Perception (DC = enemy ADC), learn one level of information from visual identification list",
  "Glide":                         "Move ship at half speed, turn distance increases by 2, add your Piloting ranks to ship's AC and TL for this round",
  "Quick Rescan":                  "Check the sensors (DC = enemy SDC), you get to hear one piece of already scanned information again",
  "Fire At Will":                  "Two shots from different weapons, -4 penalty to attack rolls",
  "Shoot":                         "Single shot from one weapon",
  "Harrying Shot":                 "Gunnery check (DC = 10 + enemy pilot rank), next ally firing a weapon at that foe this round gets advantage on the attack roll",
  "Snap Shot":                     "Single shot from one weapon, -2 penalty to attack roll",
};
export default ShipActionDescriptions;