const ShipActionDescriptions = {
  "Encourage":                     "Boost another crew member's action by +2 (+4 on crit)",
  "Taunt":                         "Select a phase, Bluff or Intimidate check vs an enemy, selected phase -2 penalty all checks for 1d4 rounds, once per ship per combat",
  "Demand":                        "Intimidate another crew member before they do an action for +4 bonus, once per target crew member per combat",
  "Hold It Together":              "Treat system as though it's critically damaged by 2 less phases for the rest of the round",
  "Divert":                        "Boost speed by 2, all science officer rolls by 2, make weapon damage dice rolls 1 into 2, or restore 5% shields",
  "Patch":                         "Patch a system to reduce the effects of critical damage",
  "Maintenance Panel Access":      "Done before a Divert, Acrobatics or Athletics check, if successful the engineer can divert 2 systems instead of 1",
  "Scrying":                       "Scan an enemy ship using Mysticism to learn one level of things about it",
  "Eldritch Shot":                 "Augment a weapon with Mysticism. If successful, that weapon gets +5 range for its next attack",
  "Precognition":                  "Give the pilot a +2 circumstance bonus to Piloting at the beginning of the Helm phase",
  "Swift Kick":                    "Engineering check, select 1 system, treat it as though it were 1 step less damaged for the rest of round, once per system per combat",
  "Stunt":                         "<strong>Back Off:</strong> Move half speed in reverse without turning<br/><strong>Barrel Roll:</strong> Move half speed and flip upside-down, swaps port and starboard weapon arcs for this round<br/><strong>Evade:</strong> Normal movement, +2 circumstance bonus to AC and TL until next round<br/><strong>Flip and Burn:</strong> Move half speed without turning, then rotate 180 degrees<br/><strong>Flyby:</strong> Normal movement, move through enemy's hex without provoking an attack<br/><strong>Ramming Speed:</strong> Move through enemy's hex and roll gunnery check to attempt a collision (damages both ships), turn distance is increased by 2 while ramming<br/><strong>Slide:</strong> Diagonal slide in forward-port or forward-starboard direction without turning<br/><strong>Turn In Place:</strong> Turn to face any direction without moving",
  "Fly":                           "Normal movement",
  "Maneuver":                      "Attempt a Piloting check to move with tighter turns (turn distance reduce by 1)",
  "Target System":                 "Make attacks against a target system crit on a 19 as well as a 20",
  "Balance":                       "Rebalance the shields using Computers check",
  "Scan":                          "Scan an enemy ship using Computers to learn one level of things about it",
  "Hard Turn":                     "Acrobatics or Athletics check, pilot gets to make a single turn with a +1 turn range",
  "Manual Realignment":            "Acrobatics or Athletics check, science officer gets 2 levels of information from a scan instead of 1",
  "Visual Identification":         "Computers/Engineering/Perception, learn one level of information from visual identification list",
  "Glide":                         "Move ship at half speed, turn distance increases by 2, add your Piloting ranks to ship's AC and TL for this round",
  "Quick Rescan":                  "Check the sensors, you get to hear one piece of already scanned information again",
  "Fire At Will":                  "Two shots from different weapons, -4 penalty to attack rolls",
  "Shoot":                         "Single shot from one weapon",
  "Harrying Shot":                 "Gunnery check, next ally firing a weapon at that foe this round gets advantage on the attack roll",
  "Snap Shot":                     "Single shot from one weapon, -2 penalty to attack roll",
};
export default ShipActionDescriptions;