const SpellDescriptions = {
  "Conjure Grenade":        "Conjure and throw a piercing grenade",
  "Daze":                   "Short-circuit the mind of a humanoid creature so it can't perform actions",
  "Detect Magic":           "Detect all magical spells, effects, items, objects, and hybrid items in the area",
  "Detect Tech":            "Detect all technological items with charges in the area",
  "Embrace of the Void":    "Wrap the target in coldness, dealing cold damage",
  "Energy Ray":             "Fire a ray of acid, cold, electricity or fire at an opponent",
  "Fatigue":                "Cause a non-fatigued opponent to become fatigued",
  "Hold Person":            "Paralyzes an opponent, freezing them in place",
  "Holographic Interface":  "Interface with an unfamiliar or interfaceless computer",
  "Inflict Pain":           "Cause an opponent to feel agonizing pain",
  "Jolting Surge":          "Melee attack that makes an electrical device surge out of control",
  "Lesser Confusion":       "Make an opponent confused for 1 round",
  "Lesser Entangle":        "Creatures entering the target area become entangled",
  "Life Bubble":            "Give the target an artificial bubble of clean air",
  "Mending":                "Repair damaged objects and constructs",
  "Mind Thrust":            "Overload the mind of an intelligent creature",
  "Moment's Hesitation":    "Make a creature staggered for 1 round",
  "Psychokinetic Hand":     "Lift and move an unattended object by pointing at it",
  "Reflecting Armor":       "Allows you to reflect a single attack back at the attacker",
  "Remote Operation":       "Remotely control a technological target",
  "Spark":                  "Set the surface of a flammable object you touch on fire",
  "Telekinetic Projectile": "Fling an unattended object weighing up to 5 lbs at an opponent",
  "Transfer Charge":        "Transfer charges between identical batteries",
  "Wisp Ally":              "Create a floating wisp to distract your enemies",
};
export default SpellDescriptions;