const SpellDescriptions = {
  "Adhere":                 "Create a molecular bond between an object and a surface",
  "Conjure Grenade":        "Conjure and throw a piercing grenade",
  "Corrosive Haze":         "Convert nearby water vapour into a cloud of deadly acid",
  "Daze":                   "Short-circuit the mind of a humanoid creature so it can't perform actions",
  "Detect Magic":           "Detect most forms of magic in the surrounding area",
  "Detect Tech":            "Detect all technological items with charges in the area",
  "Dimension Door":         "Transfer yourself and up to four others to any other spot in range",
  "Dispel Magic":           "End an ongoing spell that was cast on a creature or object",
  "Embrace of the Void":    "Wrap the target in coldness, dealing cold damage",
  "Energy Ray":             "Fire a ray of acid, cold, electricity or fire at an opponent",
  "Enervation":             "Shoot a black ray at a target, temporarily reducing their level",
  "Explosive Blast":        "Transform a used battery into an explosive device",
  "Fatigue":                "Cause a non-fatigued opponent to become fatigued",
  "Fear":                   "Unlock the deepest nightmares of one or more targets",
  "Heat Leech":             "Drain the heat from all creatures and objects in the area",
  "Hold Monster":           "Paralyzes any living creature, freezing them in place",
  "Hold Person":            "Paralyzes another person, freezing them in place",
  "Holographic Interface":  "Interface with an unfamiliar or interfaceless computer",
  "Inflict Pain":           "Cause an opponent to feel agonizing pain",
  "Jolting Surge":          "Melee attack that makes an electrical device surge out of control",
  "Lesser Confusion":       "Make an opponent confused for 1 round",
  "Lesser Entangle":        "Creatures entering the target area become entangled",
  "Life Bubble":            "Give the target an artificial bubble of clean air",
  "Magic Missile":          "Fire 2-3 missiles that can't miss and deal force damage",
  "Mending":                "Repair damaged objects and constructs",
  "Mind Thrust":            "Overload the mind of an intelligent creature",
  "Mindlink":               "Link minds with a willing creature to communicate rapidly",
  "Moment's Hesitation":    "Make a creature staggered for 1 round (they lose an action)",
  "Mystic Cure":            "Restore hit points to a target creature",
  "Psychokinetic Hand":     "Lift and move an unattended object by pointing at it",
  "Reflecting Armor":       "Allows you to reflect a single attack back at the attacker",
  "Remote Operation":       "Remotely control a technological target",
  "Spark":                  "Set the surface of a flammable object you touch on fire",
  "Supercharge Weapon":     "Make the next attack of a target weapon do extra damage",
  "Telekinetic Projectile": "Fling an unattended object weighing up to 5 lbs at an opponent",
  "Telepathic Message":     "Send a short telepathic message and hear simple replies",
  "Token Spell":            "Perform a very simple magical effect",
  "Transfer Charge":        "Transfer charges between identical batteries",
  "Verdant Code":           "Turn data within a device into plant matter",
  "Wisp Ally":              "Create a floating wisp to distract your enemies",
};
export default SpellDescriptions;